# Generated by Django 5.1.1 on 2024-09-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_email_booking_name_booking_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
