# Generated by Django 5.1.1 on 2024-09-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Hourly rate for the studio', max_digits=10),
        ),
    ]
