# Generated by Django 5.1.1 on 2024-09-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_studio_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='benefits',
            field=models.TextField(default='Rehersal', help_text='Comma-separated list of recommended activities for the studio (e.g. Yoga, Photography, Dance)'),
        ),
        migrations.AddField(
            model_name='studio',
            name='blurb',
            field=models.TextField(default='Please enter a brief description of the studio', max_length=150),
        ),
    ]
